In [1]:
import numpy as np

In [3]:
arr = np.array([1,4,3,5,7])
result = arr ** 2 #vectorized operation
result

array([ 1, 16,  9, 25, 49])

In [11]:
result = np.array([5,6,7,8])
result + 10 # Broadcasting : 10 is added to all elements

array([15, 16, 17, 18])

In [16]:
arr1 = np.array([[3,2,2],[5,6,7]])
arr2 = np.array([1,4,5])
arr = arr1 + arr2 #Broadcasting arr2 across arr1
print(arr)

[[ 4  6  7]
 [ 6 10 12]]


In [18]:
data = np.array([[10,20,30],
                 [15,25,35],
                 [20,30,40],
                 [25,35,45],
                 [30,40,50]])
mean = data.mean(axis=0)
std = data.std(axis=0)

normalized_data = (data - mean) / std
print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
