In [1]:
import numpy as np

In [3]:
!pip install numpy

In [8]:
arr = np.array([1,2,6,7,8]) #1D array 

In [9]:
arr

array([1, 2, 6, 7, 8])

#### -> There is a list of lists in it. so this will be a 2D array.
-> unlike lists, all elements must have the same data type.

In [10]:
arr1=np.array([[1,2,3],[7,8,9]]) # 2D array

In [11]:
arr1

array([[1, 2, 3],
       [7, 8, 9]])

In [12]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((2,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.full((4,4),8) # 4x4  filled with 8

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [18]:
np.eye(5) #5x5 identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.arange(1,101,9) #(start,end,step) 1+9=10,10+9=19

array([  1,  10,  19,  28,  37,  46,  55,  64,  73,  82,  91, 100])

In [25]:
np.arange(0,11,2) # print even numbers
                  #like range(n,n-1)

array([ 0,  2,  4,  6,  8, 10])

#### these are mostly the functions that you will use in numpy.
--> shortcut method to generate array. directly provies by numpy.

In [28]:
np.linspace(0, 1, 5) # evenly spaced

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [29]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [30]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

myarr

In [32]:
myarr.shape # (4,3) -> 4 row 3 columns

(4, 3)

In [33]:
myarr.size # 12-> total elements

12

#### list -> 1D array, 
#### list of list -> 2D array, 
#### list of list of list -> 3D array

In [36]:
myarr.ndim # 2 -> 2D array

2

In [38]:
myarr.dtype

dtype('int64')

In [39]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]], dtype='float32') # Explicit type

In [40]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 12., 13.]], dtype=float32)

In [46]:
n = myarr.astype('int32') # convert float to int

In [48]:
n

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]], dtype=int32)

In [47]:
n.dtype

dtype('int32')

In [45]:
myarr.dtype

dtype('float32')

In [49]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [50]:
myarr.shape

(4, 3)

In [53]:
reshaped = myarr.reshape(3,4)
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 11, 12, 13]])

In [54]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [55]:
myarr.reshape((2,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 11, 12, 13]])

#### convert 2D -> 1D
#### flatten = arr.flatten() 
arr mins your array name -> myarr

In [57]:
myarr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])