In [2]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [3]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [4]:
flat = arr.flatten()

In [5]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [6]:
print(flat[0])

1


In [7]:
flat[3:6]

array([4, 5, 6])

In [8]:
print(flat[-1])

13


In [9]:
flat[:5] # sa5me as flat[0:]

array([1, 2, 3, 4, 5])

In [10]:
flat[3:] # same as flat[3:len(array)]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [11]:
flat[::2] # every 2nd element

array([ 1,  3,  5,  7,  9, 12])

#### slicing returns a view, not a copy! Changes affect the original array.**

In [12]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

#### using copy method

In [56]:
b = flat[4:7].copy() # this is not slice because we are copy method to get the copy.

In [57]:
b

array([44466, 44466,     7])

In [61]:
b[0] = 444490

In [62]:
b

array([444490,  44466,      7])

In [63]:
flat

array([    1,     2,     3,     4, 44466, 44466,     7,     8,     9,
          11,    12,    13])

#### fancy indexing

In [13]:
arr = np.array([1,3,4,56,78,65,43,54,23,80])

In [14]:
arr[[1,3,6]]

array([ 3, 56, 43])

#### Boolean masking

In [69]:
arr[arr>23]

array([56, 78, 65, 43, 54, 80])