In [2]:
import numpy as np
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr[0] # Axis 0(rows) 

array([1, 2, 3])

In [5]:
np.sum(arr, axis=0) # axis=0 correspond to rows(Down each column) 

array([12, 15, 18])

In [6]:
np.sum(arr, axis=1) # axis=1 correspond to columns(across each row)

array([ 6, 15, 24])

In [10]:
print(arr[1][2])

6


In [13]:
print(arr[1,2])

6


In [16]:
arr[0:2,1:3] # Extracts first 2 mins(0,1) rows  and last 2 mins(1,2)columns

array([[2, 3],
       [5, 6]])

In [17]:
arr3D=np.array([
    [[1,2,3],[4,5,6]],
    [[5,6,7],[0,1,2]]
])

In [18]:
arr3D

array([[[1, 2, 3],
        [4, 5, 6]],

       [[5, 6, 7],
        [0, 1, 2]]])

In [20]:
arr3D.shape #(2,2,3)->2 blocks,2 rows,2 columns

(2, 2, 3)

In [21]:
print(arr3D[0,1,2])

6


In [25]:
print(arr3D[:,0,1:])

[[2 3]
 [6 7]]


In [26]:
arr3D[:,0,1:] = 0

In [28]:
arr3D

array([[[1, 0, 0],
        [4, 5, 6]],

       [[5, 0, 0],
        [0, 1, 2]]])