#### -> numpy arrays are scalable And the more the scale is increased, the more it is optimized.
#### -> Numpy is only made for numerical computation.
#### -> numpy is faster and clean.

In [13]:
# python zip explained
l1 = [1,2,3]
l2 = [4,5,6]
list(zip(l1,l2))

[(1, 4), (2, 5), (3, 6)]

In [11]:
# using python lists
import numpy as np
import time

size = 1_000_000_0
l1 = list(range(size))
l2 = list(range(size))

start = time.time()
add = [x+y for x, y in zip(l1,l2)]
end = time.time()
print(add[0:10])

print(end - start)


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
1.5245895385742188


In [12]:
# using numpy arrays
import numpy as np
import time

size = 1_000_000_0
l1 = np.array(list(range(size)))
l2 = np.array(list(range(size)))

start = time.time()
add = l1 + l2
end = time.time()
print(add[0:10])

print(end - start)

[ 0  2  4  6  8 10 12 14 16 18]
0.23968195915222168


In [18]:
np.array([2,4,5,6,7,"shaili"]) # <U21-> unicode string array

array(['2', '4', '5', '6', '7', 'shaili'], dtype='<U21')

In [26]:
print(np.array([[1,2,3],[4,5,6]])) # 2D array
print(np.array([[2,3],[4,5]])) # you will deal with only 2 dimensions.

[[1 2 3]
 [4 5 6]]
[[2 3]
 [4 5]]


In [30]:
arr = np.array([[1,2,3],[4,5,6]])
type(arr)

numpy.ndarray

In [32]:
arr.shape #(2,2)-> 2 rows 3 column

(2, 3)

#### The number of bytes of our numpy list, it took significantly less bytes of the numpy is very smart in the way it stores data.

In [34]:
import sys
list_data = list(range(1000))
numpy_data = np.array(list_data)
print("python list size:",sys.getsizeof(list_data)*len(list_data),"bytes")
print("Numpy array size:",numpy_data.nbytes,"bytes")

python list size: 8056000 bytes
Numpy array size: 8000 bytes
